In [1]:
import numpy as np

an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(type(an_array))              # The type of an ndarray is: "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [4]:
print(an_array[0], an_array[1], an_array[2]) 

3 33 333


In [5]:
an_array[0] =888            

print(an_array)

[888  33 333]


In [6]:
another = np.array([[11,12,13],[21,22,23]])   
print(another)  
print("The shape is 2 rows, 3 columns: ", another.shape)                    
print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 ,  12 ,  21


In [7]:
import numpy as np

# create a 2x2 array of zeros
ex1 = np.zeros((2,2))      
print(ex1)  

[[0. 0.]
 [0. 0.]]


In [8]:
ex2 = np.full((2,2), 9.0)  
print(ex2)   

[[9. 9.]
 [9. 9.]]


In [9]:
ex3 = np.eye(2,2)
print(ex3) 

[[1. 0.]
 [0. 1.]]


In [10]:
ex4 = np.ones((1,2))
print(ex4)    

[[1. 1.]]


In [11]:
ex5 = np.random.random((2,2))
print(ex5)

[[0.85777412 0.61204696]
 [0.51761455 0.16532779]]


# Slice indexing:

In [12]:
import numpy as np

an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [13]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [14]:
print("Before:", an_array[0, 1])     
a_slice[0, 0] = 1000
print("After:", an_array[0, 1])    

Before: 12
After: 1000


In [15]:
row_rank1 = an_array[1, :]    
print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [16]:
row_rank2 = an_array[1:2, :]   
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [17]:
print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  
print()
print(col_rank2, col_rank2.shape)  


[1000   22   32] (3,)

[[1000]
 [  22]
 [  32]] (3, 1)


In [18]:
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [19]:
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [20]:
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [21]:
print('Values in the array at those indices: ',an_array[row_indices, col_indices])

Values in the array at those indices:  [11 22 33 41]


In [22]:
an_array[row_indices, col_indices] += 100000

print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


# Boolean Indexing

In [23]:
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [24]:
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [25]:
print(an_array[filter])

[21 22 31 32]


In [26]:
an_array[(an_array % 2 == 0)]

array([12, 22, 32])

In [27]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


# Datatypes:

In [28]:
ex1 = np.array([11, 12]) # Python assigns the  data type
print(ex1.dtype)

int32


In [29]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

float64


In [30]:
ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(ex3.dtype)

int64


In [31]:
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [32]:
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


# Arithmetic Array Operations:

In [33]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [34]:
print(x + y)        
print()
print(np.add(x, y)) 

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [35]:
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [36]:
print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [37]:
print(x / y)
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [38]:
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [39]:
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


# Basic Statistical Operations:

In [40]:
arr = 10 * np.random.randn(2,5)
print(arr)

[[13.36100777  0.13246498 13.67868783 11.97601105  7.61136597]
 [-3.22448991 -9.86540458 -1.127733   -1.35861366 14.61912016]]


In [41]:
print(arr.mean())

4.580241659742656


In [42]:
print(arr.mean(axis = 1))

[ 9.35190752 -0.1914242 ]


In [43]:
print(arr.mean(axis = 0))

[ 5.06825893 -4.8664698   6.27547741  5.3086987  11.11524307]


In [44]:
print(arr.sum())

45.80241659742656


In [45]:
print(np.median(arr, axis = 1))

[11.97601105 -1.35861366]


# Sorting:

In [46]:
unsorted = np.random.randn(10)

print(unsorted)

[-0.18117694  0.76298228 -0.72457093  0.71936696 -1.02970864 -0.70715109
  0.2604107  -0.27480579  0.61050347 -0.30768267]


In [47]:
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-1.02970864 -0.72457093 -0.70715109 -0.30768267 -0.27480579 -0.18117694
  0.2604107   0.61050347  0.71936696  0.76298228]

[-0.18117694  0.76298228 -0.72457093  0.71936696 -1.02970864 -0.70715109
  0.2604107  -0.27480579  0.61050347 -0.30768267]


In [48]:
unsorted.sort() 

print(unsorted)

[-1.02970864 -0.72457093 -0.70715109 -0.30768267 -0.27480579 -0.18117694
  0.2604107   0.61050347  0.71936696  0.76298228]


# Finding Unique elements:

In [49]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


In [50]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [51]:
print( np.intersect1d(s1, s2) ) 

['bulb' 'chair']


In [52]:
print( np.union1d(s1, s2) )

['bulb' 'chair' 'desk' 'lamp']


In [53]:
print( np.setdiff1d(s1, s2) )

['desk']


In [54]:
print( np.in1d(s1, s2) )

[False  True  True]


# Broadcasting:

In [55]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [56]:
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [57]:
y = start + add_rows  
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [58]:
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [59]:
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [60]:
add_scalar = np.array([1])  
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [61]:
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [62]:
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [63]:
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


# Speedtest: ndarrays vs lists

In [64]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

In [65]:
nd_array = arange(size)
print( type(nd_array) )

<class 'numpy.ndarray'>


In [66]:
nd_array = arange(size)
print( type(nd_array) )

<class 'numpy.ndarray'>


In [67]:
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000320 seconds


In [68]:
a_list = list(range(size))
print (type(a_list) )

<class 'list'>


In [69]:
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

Time taken by list:  0.019966 seconds


# Binary Format:

In [70]:
x = np.array([ 23.23, 24.24] )

In [71]:
np.save('an_array', x)

In [72]:
np.load('an_array.npy')

array([23.23, 24.24])

# Text Format:

In [73]:
np.savetxt('array.txt', X=x, delimiter=',')

In [75]:
np.loadtxt('array.txt', delimiter=',')

array([23.23, 24.24])

# Dot Product on Matrices:

In [76]:
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [77]:
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))

180

180


In [78]:
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))

[18 18]

[18 18]


# Sum:

In [79]:
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1)) 

66


In [80]:
print(np.sum(ex1, axis=0))

[32 34]


In [81]:
print(np.sum(ex1, axis=1))

[23 43]


# Element-wise Functions:

In [82]:
x = np.random.randn(8)
x

array([-0.16205369, -0.32025286,  2.11026959,  0.3153534 ,  0.37660819,
        1.24006998, -1.04414173,  1.02704945])

In [83]:
y = np.random.randn(8)
y

array([ 1.2944278 ,  0.43218871, -0.05169438, -0.38747035,  0.65240698,
       -0.79787458,  1.88598964,  1.9126449 ])

In [84]:
np.maximum(x, y)

array([1.2944278 , 0.43218871, 2.11026959, 0.3153534 , 0.65240698,
       1.24006998, 1.88598964, 1.9126449 ])

# Reshaping array:

In [85]:
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [86]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Transpose:

In [87]:
ex1 = np.array([[11,12],[21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

# Where(), any(), all()

In [88]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [89]:
out = np.where(filter, x_1, y_1)
print(out)

[ 1 22  3 44  5]


In [90]:
mat = np.random.rand(5,5)
mat

array([[0.91035166, 0.53738082, 0.72015791, 0.49778377, 0.4902626 ],
       [0.15102843, 0.61176949, 0.76997231, 0.05462685, 0.86780842],
       [0.10486596, 0.53741715, 0.73138799, 0.10489296, 0.84019604],
       [0.7322657 , 0.7620845 , 0.88015527, 0.57934012, 0.96928579],
       [0.09413148, 0.88493238, 0.52491482, 0.94071851, 0.06635832]])

In [91]:
np.where( mat > 0.5, 1000, -1)

array([[1000, 1000, 1000,   -1,   -1],
       [  -1, 1000, 1000,   -1, 1000],
       [  -1, 1000, 1000,   -1, 1000],
       [1000, 1000, 1000, 1000, 1000],
       [  -1, 1000, 1000, 1000,   -1]])

In [92]:
arr_bools = np.array([ True, False, True, True, False ])

In [93]:
arr_bools.any()

True

In [94]:
arr_bools.all()

False

# Random Number Generation:

In [95]:
Y = np.random.normal(size = (1,5))[0]
print(Y)

[ 0.2510433  -0.19667206 -1.77779303  0.37666187  0.69744635]


In [96]:
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

[ 2 42 30 17]


In [97]:
np.random.permutation(Z)

array([42, 30,  2, 17])

In [98]:
np.random.uniform(size=4)

array([0.9398232 , 0.00708544, 0.75989472, 0.99992617])

In [99]:
np.random.normal(size=4)

array([0.14655806, 0.39572652, 1.85213239, 0.1723804 ])

# Merging Data Sets

In [100]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[35 39]
 [ 7  9]]

[[40 17]
 [42 24]]


In [101]:
np.vstack((K,M))

array([[35, 39],
       [ 7,  9],
       [40, 17],
       [42, 24]])

In [102]:
np.hstack((K,M))

array([[35, 39, 40, 17],
       [ 7,  9, 42, 24]])

In [103]:
np.concatenate([K, M], axis = 0)

array([[35, 39],
       [ 7,  9],
       [40, 17],
       [42, 24]])

In [104]:
np.concatenate([K, M.T], axis = 1)

array([[35, 39, 40, 42],
       [ 7,  9, 17, 24]])